logo: "https://avatars.githubusercontent.com/u/11699531"
title: "MPDieckmann"
sidebar: "sidebar-widgets.html"
footer: "footer-widgets.html"

collections:
  repositories:
    output: true
    permalink: /:path/

defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      appbackground: "#eee"
      cardbackground: "#fff"
      themecolor: "#68a"
      themedforecolor: "#fff"
      layout: "default"
      author: "<a href=\"https://github.com/MPDieckmann\">MPDieckmann</a>"
  - scope:
      path: ""
      type: "posts"
    values:
      showmeta: "true"
      appbackground: "#eee"
      cardbackground: "#fff"
      themecolor: "#68a"
      themedforecolor: "#fff"
      layout: "default"
      author: "<a href=\"https://github.com/MPDieckmann\">MPDieckmann</a>"
  - scope:
      path: ""
      type: "repositories"
    values:
      showmeta: "true"
      appbackground: "#eee"
      cardbackground: "#fff"
      themecolor: "#68a"
      themedforecolor: "#fff"
      layout: "default"
      author: "<a href=\"https://github.com/MPDieckmann\">MPDieckmann</a>"
